CREATE TABLE IF NOT EXISTS BL_3NF.CE_COLORS(
COLOR_ID int PRIMARY KEY,
COLOR varchar(20), 
TA_INSERT_DT date, 
TA_UPDATE_DT date, 
SOURCE_SYSTEM varchar(50), 
SOURCE_ENTITY varchar(50),
SOURCE_ID varchar(50)); 
