CREATE TABLE IF NOT EXISTS BL_CL.T_MAP_COLORS (
COLOR_ID int NOT NULL,
COLOR varchar,
COLOR_SRC_NAME varchar,
TA_INSERT_DT date,
TA_UPDATE_DT date,
SOURCE_SYSTEM varchar,
SOURCE_ENTITY varchar,
SOURCE_ID varchar
);