-- procedure of load sales fact
CREATE OR REPLACE PROCEDURE BL_CL.prc_load_init_ce_sales()
LANGUAGE plpgsql
AS $$
BEGIN 
	
	CREATE TABLE IF NOT EXISTS BL_3NF.CE_SALES (
	SALE_ID INT PRIMARY KEY,
	CUSTOMER_ID INT REFERENCES BL_3NF.CE_CUSTOMERS(CUSTOMER_ID),
	EMPLOYEE_ID INT,
	MODEL_ID INT REFERENCES BL_3NF.CE_MODELS(MODEL_ID),
	PRODUCT_ID INT REFERENCES BL_3NF.CE_PRODUCTS(PRODUCT_ID),
	MMR decimal,
	AMOUNT decimal,
	DATE_ID DATE REFERENCES BL_3NF.CE_DATES(DATE_ID),
	TIME TIME,
	TA_INSERT_DT date,
	TA_UPDATE_DT date,
	SOURCE_SYSTEM varchar(50),
	SOURCE_ENTITY varchar(50),
	SOURCE_ID varchar(50)
	);

	CREATE SEQUENCE IF NOT EXISTS bl_3nf.ce_sales_id_seq START 1;
	
	ALTER TABLE bl_3nf.ce_sales 
	ALTER COLUMN sale_id SET DEFAULT nextval('bl_3nf.ce_sales_id_seq'); 

	RETURN;
END;$$;