CREATE TABLE IF NOT EXISTS BL_CL.T_MAP_BMODELS (
BMODEL_ID int NOT NULL,
BMODEL_NAME varchar(50),
BMODEL_SRC_NAME varchar(50),
TA_INSERT_DT date,
TA_UPDATE_DT date,
SOURCE_SYSTEM varchar(50),
SOURCE_ENTITY varchar(50),
SOURCE_ID varchar(50)
);