CREATE TABLE IF NOT EXISTS BL_3NF.CE_BRANDS(
BRAND_ID int PRIMARY KEY, 
BRAND varchar(20), 
TA_INSERT_DT date, 
TA_UPDATE_DT date, 
SOURCE_SYSTEM varchar(50), 
SOURCE_ENTITY varchar(50), 
SOURCE_ID varchar(50)); 
