CREATE TABLE IF NOT EXISTS BL_3NF.CE_PRODUCTS (
PRODUCT_ID int PRIMARY KEY, 
VIN varchar(17) UNIQUE, 
COLOR_ID int REFERENCES BL_3NF.CE_COLORS(COLOR_ID) NOT NULL, 
INTERIOR_ID int REFERENCES BL_3NF.CE_COLORS(COLOR_ID) NOT NULL, 
CONDITION decimal, 
ODOMETER decimal, 
STATE_ID SMALLINT REFERENCES BL_3NF.CE_STATES(STATE_ID) NOT NULL, 
TA_INSERT_DT date, 
TA_UPDATE_DT date, 
SOURCE_SYSTEM varchar(50), 
SOURCE_ENTITY varchar(50), 
SOURCE_ID varchar(50));
