CREATE TABLE IF NOT EXISTS BL_DM.DIM_CUSTOMERS (
CUSTOMER_SURR_ID INT PRIMARY KEY,
FIRSTNAME VARCHAR(30),
LASTNAME VARCHAR(30),
EMAIL VARCHAR(50),
TA_INSERT_DT DATE,
TA_UPDATE_DT DATE,
SOURCE_SYSTEM VARCHAR(50),
SOURCE_ENTITY VARCHAR(50),
SOURCE_ID VARCHAR(50)
);