BEGIN;

INSERT INTO BL_DM.DIM_CUSTOMERS (CUSTOMER_SURR_ID, FIRSTNAME, LASTNAME, EMAIL, TA_INSERT_DT, TA_UPDATE_DT, SOURCE_SYSTEM, SOURCE_ENTITY, SOURCE_ID)

SELECT -1, 'n. a.', 'n. a.', 'n. a.', '1-1-1900', '1-1-1900', 'MANUAL', 'MANUAL', 'n. a.'
WHERE NOT EXISTS (SELECT 1 FROM bl_dm.dim_customers WHERE customer_surr_id = -1)
RETURNING *;

COMMIT;