CREATE TABLE IF NOT EXISTS BL_3NF.CE_MODELS (
MODEL_ID int PRIMARY KEY, 
MODEL varchar(50), 
BRAND_ID SMALLINT REFERENCES BL_3NF.CE_BRANDS(BRAND_ID) NOT NULL, 
BODY varchar(50), 
TRANSMISSION varchar(50), 
YEAR int2, 
TA_INSERT_DT date, 
TA_UPDATE_DT date, 
SOURCE_SYSTEM varchar(50), 
SOURCE_ENTITY varchar(50), 
SOURCE_ID varchar(50));
