CREATE TABLE IF NOT EXISTS BL_3NF.CE_CUSTOMERS (
CUSTOMER_ID int PRIMARY KEY, 
FIRSTNAME varchar(30), 
LASTNAME varchar(30), 
EMAIL varchar(50), 
TA_INSERT_DT date, 
TA_UPDATE_DT date, 
SOURCE_SYSTEM varchar(50), 
SOURCE_ENTITY varchar(50), 
SOURCE_ID varchar(50));
