BEGIN;

INSERT INTO BL_DM.DIM_PRODUCTS (PRODUCT_SURR_ID, VIN, COLOR, COLOR_ID, INTERIOR, INTERIOR_ID, ODOMETER, CONDITION, STATE, 
								STATE_ID, TA_INSERT_DT, TA_UPDATE_DT, SOURCE_SYSTEM, SOURCE_ENTITY, SOURCE_ID)
SELECT -1, 'n. a.', 'n. a.', -1, 'n. a.', -1, -1, -1, 'n. a.', -1, '1-1-1900', '1-1-1900', 'MANUAL', 'MANUAL', 'n. a.'
WHERE NOT EXISTS (
SELECT * FROM BL_DM.DIM_PRODUCTS p WHERE p.PRODUCT_SURR_ID = -1
)
RETURNING *;

COMMIT;