BEGIN;
INSERT INTO BL_3NF.CE_DATES (DATE_ID, DAY, MONTH, YEAR)

	SELECT d::DATE, EXTRACT(DAY FROM d), EXTRACT(MONTH FROM d), EXTRACT(YEAR FROM d)
	FROM generate_series('2010-01-01'::DATE, '2025-01-01'::DATE, '1 day') d
	LEFT JOIN BL_3NF.CE_DATES t ON d::DATE = t.DATE_ID
	WHERE t.DATE_ID IS NULL
	
RETURNING *;
COMMIT;

--SELECT count(*) FROM public.ce_dates;