CREATE TABLE IF NOT EXISTS BL_DM.DIM_MODELS (
MODEL_SURR_ID INT PRIMARY KEY,
MODEL VARCHAR(50),
BRAND VARCHAR(50),
BRAND_ID SMALLINT,
YEAR SMALLINT,
BODY VARCHAR(30),
TRANSMISSION VARCHAR(30),
TA_INSERT_DT DATE,
TA_UPDATE_DT DATE,
SOURCE_SYSTEM VARCHAR(50),
SOURCE_ENTITY VARCHAR(50),
SOURCE_ID VARCHAR(50)
);