CREATE TABLE IF NOT EXISTS BL_CL.T_MAP_BRANDS (
BRAND_ID int NOT NULL,
BRAND_NAME varchar,
BRAND_SRC_NAME varchar,
TA_INSERT_DT date,
TA_UPDATE_DT date,
SOURCE_SYSTEM varchar,
SOURCE_ENTITY varchar,
SOURCE_ID varchar
);