BEGIN;
INSERT INTO BL_DM.DIM_EMPLOYEES_SCD (EMPLOYEE_SURR_ID, FIRSTNAME, LASTNAME, EMAIL, BADGE, START_DT, END_DT, 
									IS_ACTIVE, TA_INSERT_DT, TA_UPDATE_DT, SOURCE_SYSTEM, SOURCE_ENTITY, SOURCE_ID)
SELECT -1, 'n. a.', 'n. a.', 'n. a.', 'n. a.', '1-1-1900', '9999-12-31'::date, True, '1-1-1900', '1-1-1900', 'MANUAL', 'MANUAL', 'n. a.'
WHERE NOT EXISTS (
SELECT * FROM BL_DM.DIM_EMPLOYEES_SCD e WHERE e.EMPLOYEE_SURR_ID = -1
)
RETURNING *;
COMMIT;